# Assignment 3

Name: Aziz Sayyad
Roll: 381069
PRN: 22420090
Batch: A3

Perform text cleaning, perform lemmatization (any method), remove stop words (any method), label encoding. Create representations using TF-IDF. Save output.

In [2]:
!pip install nltk scikit-learn pandas

Requirement already satisfied: nltk in c:\users\aziz\appdata\roaming\python\python312\site-packages (3.9.1)
Requirement already satisfied: scikit-learn in c:\users\aziz\appdata\roaming\python\python312\site-packages (1.5.2)
Requirement already satisfied: pandas in c:\users\aziz\appdata\roaming\python\python312\site-packages (2.2.2)
Requirement already satisfied: click in c:\users\aziz\appdata\roaming\python\python312\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\aziz\appdata\roaming\python\python312\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\aziz\appdata\roaming\python\python312\site-packages (from nltk) (4.66.5)
Requirement already satisfied: numpy>=1.19.5 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\aziz\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\aziz\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)

In [3]:
# imports

import nltk
import re
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [4]:
# sample dataset

data = {
    "text": [
        "Data science is very interesting!",
        "I enjoy working with Python programming",
        "Artificial intelligence is the future",
        "Python is popular for data analysis"
    ],
    "label": ["positive", "positive", "neutral", "neutral"]
}


df = pd.DataFrame(data)
df

                                      text     label
0        Data science is very interesting!  positive
1  I enjoy working with Python programming  positive
2    Artificial intelligence is the future   neutral
3      Python is popular for data analysis   neutral

In [5]:
# Text cleaning function

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text

df['clean_text'] = df['text'].apply(clean_text)
df

,text,label,clean_text
0,Data science is very interesting!,positive,data science is very interesting
1,I enjoy working with Python programming,positive,i enjoy working with python programming
2,Artificial intelligence is the future,neutral,artificial intelligence is the future
3,Python is popular for data analysis,neutral,python is popular for data analysis

In [6]:
# Stop word removal
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    return " ".join([word for word in words if word not in stop_words])

df['no_stopwords'] = df['clean_text'].apply(remove_stopwords)
df

,text,label,clean_text,no_stopwords
0,Data science is very interesting!,positive,data science is very interesting,data science interesting
1,I enjoy working with Python programming,positive,i enjoy working with python programming,enjoy working python programming
2,Artificial intelligence is the future,neutral,artificial intelligence is the future,artificial intelligence future
3,Python is popular for data analysis,neutral,python is popular for data analysis,python popular data analysis

In [7]:
# Lemmatization
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    return " ".join([lemmatizer.lemmatize(word) for word in words])

df['lemmatized_text'] = df['no_stopwords'].apply(lemmatize_text)
df

,text,label,clean_text,no_stopwords,lemmatized_text
0,Data science is very interesting!,positive,data science is very interesting,data science interesting,data science interesting
1,I enjoy working with Python programming,positive,i enjoy working with python programming,enjoy working python programming,enjoy working python programming
2,Artificial intelligence is the future,neutral,artificial intelligence is the future,artificial intelligence future,artificial intelligence future
3,Python is popular for data analysis,neutral,python is popular for data analysis,python popular data analysis,python popular data analysis

In [8]:
# Label Encoding
label_encoder = LabelEncoder()
df['encoded_label'] = label_encoder.fit_transform(df['label'])

df[['label', 'encoded_label']]

      label  encoded_label
0  positive              1
1  positive              1
2   neutral              0
3   neutral              0

In [9]:
# TF-IDF Representation
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['lemmatized_text'])

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df

,analysis,artificial,data,enjoy,future,intelligence,interesting,popular,programming,python,science,working
0,0.000000,0.00000,0.486934,0.000000,0.00000,0.00000,0.617614,0.000000,0.000000,0.000000,0.617614,0.000000
1,0.000000,0.00000,0.000000,0.525473,0.00000,0.00000,0.000000,0.000000,0.525473,0.414289,0.000000,0.525473
2,0.000000,0.57735,0.000000,0.000000,0.57735,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.555283,0.00000,0.437791,0.000000,0.00000,0.00000,0.000000,0.555283,0.000000,0.437791,0.000000,0.000000

In [10]:
# Combine Final Output
final_df = pd.concat([df, tfidf_df], axis=1)
final_df

,text,label,clean_text,no_stopwords,lemmatized_text,encoded_label,analysis,artificial,data,enjoy,future,intelligence,interesting,popular,programming,python,science,working
0,Data science is very interesting!,positive,data science is very interesting,data science interesting,data science interesting,1,0.000000,0.00000,0.486934,0.000000,0.00000,0.00000,0.617614,0.000000,0.000000,0.000000,0.617614,0.000000
1,I enjoy working with Python programming,positive,i enjoy working with python programming,enjoy working python programming,enjoy working python programming,1,0.000000,0.00000,0.000000,0.525473,0.00000,0.00000,0.000000,0.000000,0.525473,0.414289,0.000000,0.525473
2,Artificial intelligence is the future,neutral,artificial intelligence is the future,artificial intelligence future,artificial intelligence future,0,0.000000,0.57735,0.000000,0.000000,0.57735,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Python is popular for data analysis,neutral,python is popular for data analysis,python popular data analysis,python popular data analysis,0,0.555283,0.00000,0.437791,0.000000,0.00000,0.00000,0.000000,0.555283,0.000000,0.437791,0.000000,0.000000

In [11]:
# Save Output to File
final_df.to_csv("assignment3_output.csv", index=False)
print("File saved successfully!")

File saved successfully!